### PR TITLE
Add testing notes to README.md

### PR DESCRIPTION
**Pull request by jormon**
Tell people about the `stub` option, it makes testing with this library a lot simpler.

Probably should go on your website too, but I don't think I can edit that.

### CODE REVIEW

**Comment by zeke** [comment]
+1 for landing this note in the README.

The `stub` option is documented at https://segment.com/docs/libraries/ruby/#performance, but it's not really a performance thing. I missed it in that document and ended up finding the `stub` feature by doing a GitHub issues search for 'testing'.

**Comment by jormon** [comment]
@segmentio-prod is there something more I need to do for this to be considered?

**Comment by yields** [comment]
thanks!

**Comment by zeke** [comment]
:balloon:

**Pull request merged**
