### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by Lucasosf**
This PR contains the items below:
- Fix typo
- Change the usage section to be more easy to understand
- Add the alias call to the usage section because I think it's very important.

Thanks =)

### CODE REVIEW

**Comment by Lucasosf** [comment]
please check @calvinfo @travisjeffery

**Comment by Lucasosf** [comment]
May you could check it please? @calvinfo @travisjeffery

**Comment by nettofarah** [comment]
Hey, @Lucasosf. Thanks for updating our Readme and sorry for the delay.

**Comment by Lucasosf** [comment]
Nice, thanks =)

**Pull request merged**
