### PR TITLE
Rename `Segment` namespace to `SegmentIO` to reduce collision probability

### LINKED ISSUE #256: ::Segment is too generic a namespace
Hello,

We have a product with its own concept of `Segment` unrelated to Segment-the-service. In order to use this gem we've had to fork and rename `::Segment` to `::SegmentIO`. Would you consider making this change, or accepting a PR for the change?

### PR DESCRIPTION
**Pull request by taschetto**
Fixes #256.

cc @iain-bryson

### CODE REVIEW

**Comment by taschetto** [comment]
Can we move this forward, please? @nd4p90x @pooyaj @MichaelGHSeg

**Comment by MichaelGHSeg** [comment]
Unfortunately, after discussing this internally, we decided we won't be able to rename the namespace.  

You may be able to work around it in your code with an approach like this: https://stackoverflow.com/questions/11091740/is-it-possible-to-make-an-alias-for-a-module-in-ruby

**Comment by taschetto** [comment]
Thanks for the feedback @MichaelGHSeg

**Comment by JewelSam** [comment]
Hello guys 
I guess this change was mistakenly added to [the changelog of v2.5.0](https://github.com/segmentio/analytics-ruby/blob/master/History.md#250--2024-07-17) which is a bit confusing.

**Comment by nd4p90x** [comment]
Thanks for letting us know

**Pull request closed without merging**
