### PR TITLE
Handle HTTP status code failures

### PR DESCRIPTION
**Pull request by rohitpaulk**
~Includes changes from #130 and #131. View https://github.com/rohitpaulk/analytics-ruby/pull/6 for a diff excluding changes from #130 and #131.~ Rebased on master.

### CODE REVIEW

**Comment by f2prateek** [comment]
Awesome, I had to manually resolve some conflicts, mind taking a second look and letting me know if everything looks ok?

**Comment by f2prateek** [comment]
cc @rohitpaulk

**Comment by rohitpaulk** [comment]
Hmm, something doesn't look right - I see the same block repeated twice. 

screen shot 2017-12-01 at 12 06 11 pm

Cherry-picking the required commits to a branch off master...

**Comment by rohitpaulk** [comment]
> Cherry-picking the required commits to a branch off master...

Done.

**Comment by f2prateek** [comment]
Oops, didn't notice the repeating block there. Are there some linters we could possibly add here so we can catch those via our CI? 

Thanks for updating the code, looks good to me!

**Comment by rohitpaulk** [comment]
> Oops, didn't notice the repeating block there. Are there some linters we could possibly add here so we can catch those via our CI?

The CI should've caught it, it looks like Travis wasn't triggered (don't know why) on the commit you'd pushed. I've been observing this lately, very often I have to close + reopen a PR to get the CI hooks to trigger.

**Comment by f2prateek** [comment]
Ah interesting, good to know!

**Pull request merged**
