### PR TITLE
Bump active support

### PR DESCRIPTION
**Pull request by ejcx**

### CODE REVIEW

**Comment by nettofarah** [comment]
Just saw the big warning on the main page 😅

**Comment by ejcx** [comment]
@nettofarah I don't know anything about ruby. I am just doing what the UI suggested me to do =[

**Comment by nettofarah** [comment]
I think this will actually be fine :)
Let's see if the build passes

**Comment by ejcx** [comment]
Just verified the tests pass with the old code.

**Comment by f2prateek** [comment]
We have a contractor starting soon (hopefully). I'll get them to look into this.

**Comment by f2prateek** [comment]
Closed by #128

**Pull request closed without merging**
