### PR TITLE
enable-overriding-transport-options Pass options when initializing Transport

### PR DESCRIPTION
**Pull request by annc128**
This change will allow users to override the default options so the library can be more flexible

### CODE REVIEW

**Comment by annc128** [comment]
Hi @pooyaj, I was wondering if I can get your feedback on this PR? Thank you!

**Review by nd4p90x — APPROVED** [review]

**Comment by annc128** [comment]
@nd4p90x thanks for approving, I was wondering if the new version of gem will get published soon?

**Comment by nd4p90x** [comment]
> @nd4p90x thanks for approving, I was wondering if the new version of gem will get published soon?

We are working on this now :)

**Comment by annc128** [comment]
Awesome, thank you!

**Comment by pooyaj** [comment]
@annc128 New version ( 2.4.0 ) has been released!

**Comment by annc128** [comment]
@pooyaj Much appreciated

**Pull request merged**
