### PR TITLE
Version 2.2.4.pre + release tagged commits via Travis

### PR DESCRIPTION
**Pull request by rohitpaulk**

### CODE REVIEW

**Comment by rohitpaulk** [comment]
@f2prateek We'll need to add the RubyGems API key to Travis, as mentioned in https://docs.travis-ci.com/user/deployment/rubygems/ (`travis encrypt --add deploy.api_key`)

**Comment by rohitpaulk** [comment]
Once that's done, we can try following the steps in `RELEASING.md`.

**Comment by f2prateek** [comment]
awesome! I have to hunt down the keys to our rubygems account, so will take me a while set this up, I'll try to get it done this week.

**Comment by f2prateek** [comment]
hey @rohitpaulk, we got the ruby gems credentials and I've added them to Travis now. Could you rebase against master and I can merge in these changes!

**Comment by f2prateek** [comment]
Just took a second look, and the rebase was actually pretty simple!

**Comment by rohitpaulk** [comment]
The gem publish worked!

screen shot 2018-02-15 at 10 05 23 am

Wonder what the size differences are about though - I don't recall removing so much code... I'll give this a quick smoke test locally soon.

**Pull request merged**
