### PR TITLE
Client#track: respect context.library when set by client

### PR DESCRIPTION
**Pull request by rohitpaulk**
#183, rebased on master.

### CODE REVIEW

**Comment by f2prateek** [comment]
I don't know if we want to allow the `context.library` to be overridden like this, so let's hold of on this. I think the Amplitude issue should be fixed in the integration.

**Comment by mhriess** [comment]
Author of the original PR here- fwiw this appears to be the [behavior in your node library](https://github.com/segmentio/analytics-node/blob/master/index.js#L171). What is the Amplitude integration issue? Ultimately we just want a way to pass a property to Segment that will ultimately set the 'official' Amplitude Platform property.

**Comment by f2prateek** [comment]
@mhriess I think this is an oversight in the node library. Sending a custom library name breaks functionality in Segment (e.g. the debugger pretty view). 

Re: the amplitude property, I believe you can send `context.os.name` instead of `context.library.name` to show up as the platform value.

**Comment by mhriess** [comment]
Thanks @f2prateek - just tested this locally and it works. Would be awesome to add this info to the [Segment/Amplitude integration docs](https://amplitude.zendesk.com/hc/en-us/articles/217934128#mapping), would have saved us a lot of headache! FYI I also have support ticket 171219 open- looks like support doesn't have this knowledge either.

**Pull request closed without merging**
