### PR TITLE
Add an end-to-end test

### PR DESCRIPTION
**Pull request by rohitpaulk**
https://github.com/segmentio/analytics-ruby/pull/137, opened from a branch in this repository instead of my fork. The end-to-end tests _should_ be triggered on this PR.

### CODE REVIEW

**Comment by f2prateek** [comment]
Hmm - that's weird! I see this in the build:

```
Setting environment variables from repository settings
$ export RUNSCOPE_TOKEN=[secure]
$ export RUN_E2E_TESTS=[secure]
```

But looks like it failed with:

```
 Runscope error. {"meta": {"status": "error"}, "data": {}, "error": {"status": 403, "message": "You must provide a valid Authorization header to use the Runscope API.", "more_info": "https://www.runscope.com/docs/api/authentication"}}
     # ./spec/helpers/runscope_client.rb:14:in `block in requests'
```

**Comment by f2prateek** [comment]
Ref: https://segment.atlassian.net/browse/LIB-170

**Comment by rohitpaulk** [comment]
I'll try this out on my fork and report back here soon.

**Comment by f2prateek** [comment]
interestingly - the PR build failed but the push build succeeded https://cloudup.com/clabbVJ5Cm8:

**Comment by f2prateek** [comment]
@rohitpaulk so I think I might have incorrectly entered the credentials? I deleted them and added them again, and looks like tests are working now! Sorry for the mixup

**Comment by f2prateek** [comment]
All looks good from my end now! Let me know if you have any changes you want to make, otherwise we can squash and merge these as is.

**Comment by rohitpaulk** [comment]
Looks good to me too.

**Pull request merged**
